// AUTO-GENERATED by factory-content-lore pipeline. Do not edit manually.
// Regenerate with: python3 skills/factory-content-lore/lore_pipeline.py generate ...
// Manual additions: completedLines, Tova Frost NPC, narrative arc (ErikBjare/bob#801)

export interface LoreNpc {
  id: string; name: string; role: string; flavor: string;
  zone: string; lines: string[]; questId: string | null;
  /** Dialogue shown after the NPC's quest has been completed. */
  completedLines?: string[];
}

export interface LoreQuestStage {
  description: string; objective: string;
}

export interface LoreQuest {
  id: string; title: string; zone: string; giverNpc: string;
  description: string; stages: LoreQuestStage[]; reward: string;
}

export interface LoreZone {
  id: string; name: string; flavor: string; theme: string;
}

export const WORLD_NAME = "Greenfields";
export const WORLD_TAGLINE = "Greenfields: where the old powers sleep and the new ones stumble.";

export const LORE_ZONES: LoreZone[] = [
  { id: "greenfields", name: "Greenfields", flavor: "Greenfields grew up around the crossroads, one stone at a time.", theme: "town" },
  { id: "whispering_thicket", name: "Whispering Thicket", flavor: "The trees of Whispering Thicket remember things no living person does.", theme: "forest" },
  { id: "ember_ruins", name: "Ember Ruins", flavor: "Runes still glow in Ember Ruins on certain nights. No one knows why.", theme: "ruins" },
];

export const LORE_NPCS: LoreNpc[] = [
  {
    id: "greenfields_0", name: "Hessa Salt", role: "Herbalist",
    flavor: "A herbalist who reads the soil like other people read letters.",
    zone: "greenfields",
    lines: ["This soil holds secrets. The plants remember what men forget.", "Tova Frost waits in the Whispering Thicket for a message I can't send myself. Can you carry it?"],
    questId: "greenfields_quest_0",
    completedLines: ["The message reached Tova Frost. She sent word — the herbs are working.", "You showed the same dedication the crossroads demands.", "Come back when the thicket changes again. It will."],
  },
  {
    id: "greenfields_1", name: "Yola Salt", role: "Guard",
    flavor: "A dutiful guard from the greenfields area.",
    zone: "greenfields",
    lines: ["Move along. There's been trouble near the ruins lately.", "I've patrolled these walls for ten years. I'll patrol ten more."],
    questId: null,
  },
  {
    id: "whispering_thicket_0", name: "Brennan Ash", role: "Wanderer",
    flavor: "A wanderer who came from the north and hasn't stopped moving since.",
    zone: "whispering_thicket",
    lines: ["I came from the north. I don't recommend it.", "There are things in the deep ruins that don't have names yet.", "I left a journal on the thorn path before the ruins swallowed my camp. If you find it — bring it back."],
    questId: "whispering_thicket_quest_0",
    completedLines: ["The journal is found, or at least less lost. That's more than I expected.", "Walk careful through the ruins. What we found in the thicket is only the beginning.", "You've got the right instincts for this world. Don't lose them."],
  },
  {
    id: "whispering_thicket_tova", name: "Tova Frost", role: "Healer",
    flavor: "A healer who moved to the thicket to be closer to the plants she needs.",
    zone: "whispering_thicket",
    lines: ["The herbs from Greenfields have been unreliable lately. I've been waiting for word.", "If Hessa Salt sent you — thank you. The roots I needed are almost ready."],
    questId: null,
    completedLines: ["Hessa's message arrived. The treatment is working now. Tell her the thicket remembers those who help it."],
  },
  {
    id: "whispering_thicket_1", name: "Noel Stone", role: "Scholar",
    flavor: "A scholar cataloguing thorn patterns no one else bothers to document.",
    zone: "whispering_thicket",
    lines: ["The thorn patterns in these trees — they're not natural growth.", "Something shaped this forest. I have a theory, but I need more samples."],
    questId: null,
  },
  {
    id: "ember_ruins_0", name: "Brennan Vane", role: "Innkeeper",
    flavor: "An innkeeper who never expected to end up at the edge of the ruins.",
    zone: "ember_ruins",
    lines: ["Bed and board, stranger. You look like you need both.", "The shattered plaza at the heart of the ruins — nobody goes there. Nobody comes back. I need to know what's in there."],
    questId: "ember_ruins_quest_0",
    completedLines: ["You came back. Most don't.", "What you uncovered at the plaza — I'm still thinking through what it means.", "The runes were active when you left. That hasn't happened in years."],
  },
  {
    id: "ember_ruins_1", name: "Bron Crest", role: "Scholar",
    flavor: "A meticulous scholar from the ember_ruins area.",
    zone: "ember_ruins",
    lines: ["The runes on that wall are pre-Collapse. Fascinating.", "Every ruin holds a lesson. Most people just don't read them."],
    questId: null,
  },
];

export const LORE_QUESTS: LoreQuest[] = [
  { id: "greenfields_quest_0", title: "Recover the message to Tova Frost", zone: "greenfields", giverNpc: "greenfields_0", description: "Tova Frost is waiting in the Whispering Thicket. Hessa can't leave the crossroads — someone must carry the message in person.", stages: [{"description": "Hessa Salt needs someone who can walk the thicket road.", "objective": "Speak with Hessa Salt in Greenfields."}, {"description": "Tova Frost is somewhere in the Whispering Thicket, waiting for word. Find her and speak with her directly.", "objective": "Find Tova Frost in the Whispering Thicket and deliver the message."}, {"description": "Tova has the message. Hessa will want to know it arrived.", "objective": "Return to Hessa Salt in Greenfields."}], reward: "Hessa's gratitude and a knowledge of the thicket paths" },
  { id: "whispering_thicket_quest_0", title: "Track the bound journal from the thorn path", zone: "whispering_thicket", giverNpc: "whispering_thicket_0", description: "Brennan Ash left a journal in the ruins that he can't retrieve himself. It's somewhere near the old thorn path — look for it in the Ember Ruins.", stages: [{"description": "Brennan Ash last saw the journal near the ruins boundary.", "objective": "Speak with Brennan Ash in Whispering Thicket."}, {"description": "The journal is somewhere in Ember Ruins near the old path. Search the ground — it glints faintly gold.", "objective": "Recover Brennan's journal from the Ember Ruins."}, {"description": "Brennan needs to know what you found in the ruins.", "objective": "Return to Brennan Ash in Whispering Thicket."}], reward: "Brennan's maps of the northern approach" },
  { id: "ember_ruins_quest_0", title: "Excavate what happened at the shattered plaza", zone: "ember_ruins", giverNpc: "ember_ruins_0", description: "Brennan Vane needs someone to walk to the shattered plaza at the heart of the ruins and come back out. No one else will go near it.", stages: [{"description": "Brennan Vane knows the plaza but won't go near it.", "objective": "Speak with Brennan Vane in Ember Ruins."}, {"description": "The shattered plaza lies at the heart of the ruins. Something is still active there. Walk to it.", "objective": "Reach the shattered plaza at the heart of the Ember Ruins."}, {"description": "You made it out. Brennan needs to know what's still standing.", "objective": "Return to Brennan Vane in Ember Ruins."}], reward: "Brennan's trust and a room at the edge of the ruins" },
];

export function loraNpcsByZone(zoneId: string): LoreNpc[] {
  return LORE_NPCS.filter(n => n.zone === zoneId);
}

export function loreQuestByNpc(npcId: string): LoreQuest | undefined {
  return LORE_QUESTS.find(q => q.giverNpc === npcId);
}

export function loreQuestsByZone(zoneId: string): LoreQuest[] {
  return LORE_QUESTS.filter(q => q.zone === zoneId);
}

/** IDs of all main quests — used to check if the narrative chain is complete. */
export const ALL_QUEST_IDS: ReadonlyArray<string> = LORE_QUESTS.map(q => q.id);

/** Dialogue the Wandering Knight speaks after all three seals are aligned. */
export const KNIGHT_REVELATION_LINES: ReadonlyArray<string> = [
  "You did it. All three regions — the crossroads, the thicket, the ruins.",
  "The old powers aren't sleeping anymore. The runes activated because something was waiting to be found.",
  "The Collapse left pieces of itself buried in each zone. You've touched all three. Something is coming awake.",
  "This is only the beginning. But you're the first in a long time to walk the full circle.",
];
